language: php
php:
- 7.0
- 7.1
- 7.2
sudo: false
services:
- mysql
env:
  matrix:
  - SHOPWARE_VERSION="5.5"
  global:
  - PLUGIN_NAME=FfuenfNoWishlist
  - SHOPWARE_DIRECTORY="${HOME}/shopware"
  - PLUGIN_DIRECTORY="${SHOPWARE_DIRECTORY}/custom/plugins"
cache:
  directories:
  - "${HOME}/.composer/cache/files"
install:
- composer install
before_script:
- if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini;
  fi
- git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch
  ${SHOPWARE_VERSION}
- ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis
  -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
- mv ${TRAVIS_BUILD_DIR} ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
- php ${HOME}/shopware/bin/console sw:plugin:refresh
- php ${HOME}/shopware/bin/console sw:plugin:install ${PLUGIN_NAME}
- php ${HOME}/shopware/bin/console sw:plugin:activate ${PLUGIN_NAME}
- cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
script:
- composer test
- composer test-spec
after_success:
- "./build.sh $TRAVIS_TAG"
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: "${PLUGIN_NAME}*.zip"
  on:
    tags: true
  api_key:
    secure: PeZuB5cyoqF/yhWsRSQyLxddW/rs/AsDWEturG9pLobKbvesOSzcoYfrzwSzcTcYITu+lkGZPohTAyavlRujpqCDRFLnZJIamh1DTMbE6d2bFlMRzjymX9SAxgUq7Kf6CWD6WyFNRcFdhTlE1XHt+057CMEyeZt3GyV6nPmuu24ccAuLKpBJu9Qq37oIRImptfbi6F/ccJyF5E5p46YYCXv8YJzSE4+FHQ1fWfwdReds/IaFwrpuvHsKODszm7bYDDMNPDc7yLlmKRO9isAnBa/NZFZsPSu0C8Smvr63nWrj8+lP3KOM5iZvV33x6gzqDOFmbyzQVE1W/5Fv30q2NpHm5bTKDekLs3J6rtqK7C3PcLYvcrfDoh9w+dOJYLTQe33ptKv3aVb0DKy8SZTc0EqZ2aN/9GSgEDo+RtbpPJ1804ytD+uqjLxBb3NeV6uAzRWS5LuAihH/voPGZnCVp9vPAtPo9NnAlKZwTQsfPAYb7wFmjQv9/dFLmhE+YIzneRfpQKrIT5zKjYZ7PUawj8UHDoLan1boCxb6/oB63ywSLqiXI8GDwzLb7AZMBjDivmo6GhIKopKYX55CQzRXHbMDnD86aDWf/ijeWVuKjA9QHhTYlDQeeeEZjJKC4Y1JB4jvOaH1U+jbS2ARjTh98Rs2LJWSyRAQV4puVohK4Og=
notifications:
  slack:
    secure: FiS/1E2j84HWx551K9I0fOzlH3sk6/8FXG9yfIr2AKc2z0w9gH58Z6mGyTRtlmsjztLkaVytYWsGuMWvpuEyjPSPVfcqnOd6f387yh3QUvdjs99rh+pgInnP8SIuj9EkV5S9Nr1tWERyoPjC/zpCEe4+6Cq0N48kxCerp/xwdhxUTXBfInhq6hrqGkSSg3Iy2qDKGDUIUrFPW06xgPmrFX6zOVV10IaY3kjnGoYtTyJmEF+3j9tfniSrXF+HU27jVxgEPcr6Nd1P8/jKIwhSfjvIuhKvrZyxitRVblBNkgafQOxc1/uuxkE6qpayEUI6tftzyHymI8EhzprCtD7pp3qd/7l6gFEAyieZXAaSUoyDqX+nTo6uDcmCiVUlzlYz9pFIoSiYX0YP9EnGp5mlVQ0lvHlkLOf3Dlb3wX9t1f56U7jmPPtApKbhzhJIZugajhABKTvUVi3LFW0cfmhRdzWYg2UA/h+h7x+bRSGdeJXk8PN37IgVaEncKB8yWYIFakz6xCp2mnP+0cGlPSsYnlHUy/7HU+UG6LAQl/Gu2cczYCnFI0B9ERNKJS9CrtUB72WmeRl8HfsxJVEhJpEKfLM3z9Jmr2cqHNxEZs0GCMGCl7ZIEzP6HemvZ+2uw9GEDnm+58lnYsQcsYZRW9T7yk1DflRrJedE8y+WbJPbzyw=
